### PR TITLE
Rename refrepl to replace_reference to improve clarity

### PR DESCRIPTION
**Pull request by mjbear**
Rename refrepl to reference_replace to improve clarity

### CODE REVIEW

**Comment by mjbear** [comment]
resolves #4

**Comment by mjbear** [comment]
@hellt 
Or would you prefer `replace_reference` (flipping the word order)?

**Comment by mjbear** [comment]
> @hellt Or would you prefer `replace_reference` (flipping the word order)?

My preference is verb then noun when it comes to functions. :grinning:

**Comment by hellt** [comment]
yep, thats fine

**Pull request merged**
