### PR TITLE
Add Markdown linting to CI

### PR DESCRIPTION
**Pull request by mjbear**
One of a few PR items related to the linting discussion in #17
The commits became lengthy so it made sense to split across multiple PRs.

* Use markdownlint-cli2 (Node.js) to identify Markdown linting issues
* Fix Markdown linting issues
* Add GitHub Actions Markdown linting

### CODE REVIEW

**Comment by hellt** [comment]
I think I am not willing to take in a js dependency for this
let's use markdown in a container image -- https://github.com/markdownlint/markdownlint/tree/main/tools/docker

**Comment by mjbear** [comment]
@hellt
Maybe I'm wrong here ...

* If someone wants to **use** `fnsort` they don't need Node.js anything.
* Which is different than if one wants to _develop_ `fnsort`, at which point certain tools are needed to do that work and testing.
* And if one was to specify Docker container usage as part of the "local build environment" now Docker becomes a hard-fast dependency for _development_, no way around it.

At a minimum we could get the linted/fixed files and the markdownlint-cli2 config file (which is used by GitHub Actions). From that point, local development steps and a Makefile is a moot point.

**Comment by hellt** [comment]
That is correct. And I will take docker as dev dependency ahead of JS any day

**Comment by mjbear** [comment]
@hellt
I'm going to ask a few questions to get a solid direction so I can pull this Markdown piece the last few steps across the finish line.

1. Node.js Docker image ok to use or not?

(If "no" then I know I have to rework for the Ruby Docker container, which is ok, but I want to avoid reworking things for a fourth time.)

Thank you!

**Comment by mjbear** [comment]
@hellt
I've removed the Node.js package lock files and what not.
(The Docker image bits will come in the eventual PR for the makefile.)

Essentially this PR has changes to:
1. fix the Markdown files with results from linting
1. includes the markdownlint-cli2 configuration files used to lint and validate conformity

> I'd using either is fine, they must be compatible as far as their config goes. Take one that you referred to and see how it goes

I believe you're referring to the linting rules.
As I understand, [markdown-cli2](https://github.com/DavidAnson/markdownlint-cli2) uses [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint) -- the latter is based/inspired by the Ruby markdownlint project. I would expect the linting rules to be close if not identical.

I've found the markdownlint-cli2 to be more flexible in that one can specify `globs` (for file patterns to lint) right in the configuration file! (So far I haven't seen that from the Ruby version.)

The config files are different [Node.js version](https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#configuration) vs [Ruby version](https://github.com/markdownlint/markdownlint/blob/main/docs/configuration.md), but if the result is the same, how much does it matter?

I'm going to mark this one "ready for review".
If you find anything please note it here.

**Pull request merged**
